### ISSUE TITLE
IDE gives type warnings on some Client attributes

### ISSUE THREAD

**Issue by billythekid** [bendeckdavid/graphql-client#18]
**Describe the bug**

Howdy!

PHPStorm is giving type warnings when setting some params. For example if setting variables it's looking for `Array` instead of base `array` (lowercase `a`)

<img width="970" alt="Screenshot 2024-09-07 at 04 00 20" src="https://github.com/user-attachments/assets/71f2fca7-c593-449d-80cd-459f7959d744">

**Additional comments**
PR incoming for this.

**Comment by bendeckdavid** [comment]
Thanks for the change, approved.
