### ISSUE TITLE
Code is php 8 compatible only won't run on php7.4

### ISSUE THREAD

**Issue by gm-lunatix** [bendeckdavid/graphql-client#9]
**Is your feature request related to a problem? Please describe.**
First of all great package. Unfortunately it won't run on php7.4. Since the code is full of php 8 only features (constructor property promotion, 'mixed' type hinting in function argument i.e. String|Null or using match() ), you should force php v8 in the composer config file.

**Describe the solution you'd like**
A perfect solution would be to add php 7.4 compatibility.

**Additional context**
Global usage based on the packagist stats (https://stitcher.io/blog/php-version-stats-january-2022) still favors 7.x more than 50% of the time over 8.x Most laravel apps written in php7 and already live won't get the php8 upgrade option anytime soon, that's just how production app lifetime is.

**Comment by bendeckdavid** [comment]
Hi @gm-lunatix you got a really good point, I think the package should offer support for php 7.0+, next version will include it.

**Comment by arneprescher** [comment]
I would also be very happy about this
